version: '3.2'

services:
  app:
    image: portainer/portainer
    volumes:
      - /share/appdata/config/portainer:/data
   # ports:
      #- 9000:9000
    networks:
      - traefik_public
      - internal
    deploy:
      replicas: 1
      labels:
          - "traefik.frontend.rule=Host:portainer.<yourdomainhere>"
          - "traefik.enable=true"
          - "traefik.port=9000"
          - traefik.docker.network=traefik_public
          - "traefik.frontend.auth.forward.address=http://<youriphere>:8080/authorize"
          - "traefik.frontend.auth.forward.authResponseHeaders=X-FORWARDAUTH-NAME, X-FORWARDAUTH-SUB, X-FORWARDAUTH-EMAIL"
      placement:
        constraints: [node.role == manager]
    command: -H tcp://tasks.agent:9001 --tlsskipverify

  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - internal
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.13.0/24
